// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNsubJqlp51Y6BUVRm1YlCF6YtK12T-mM',
    appId: '1:125931086830:web:072f76835ce83a14f4a4ff',
    messagingSenderId: '125931086830',
    projectId: 'deepplant-5c85a',
    authDomain: 'deepplant-5c85a.firebaseapp.com',
    storageBucket: 'deepplant-5c85a.appspot.com',
    measurementId: 'G-8E01LSBPD3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByyirdnbInZm3Qwd_v770SLeSfUL8XI-0',
    appId: '1:125931086830:android:0a5970a1f9eeea9cf4a4ff',
    messagingSenderId: '125931086830',
    projectId: 'deepplant-5c85a',
    storageBucket: 'deepplant-5c85a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHjuMJ9kgRVDaKDIibPm8arkMyHX346RI',
    appId: '1:125931086830:ios:713dafbbf54912cff4a4ff',
    messagingSenderId: '125931086830',
    projectId: 'deepplant-5c85a',
    storageBucket: 'deepplant-5c85a.appspot.com',
    iosClientId: '125931086830-vnmf8ftakmn9f8av8lbedl4h8sdsbcgj.apps.googleusercontent.com',
    iosBundleId: 'com.example.deepPlantApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHjuMJ9kgRVDaKDIibPm8arkMyHX346RI',
    appId: '1:125931086830:ios:e4382de3fb876766f4a4ff',
    messagingSenderId: '125931086830',
    projectId: 'deepplant-5c85a',
    storageBucket: 'deepplant-5c85a.appspot.com',
    iosClientId: '125931086830-fsqqrv305jg6ck34mol4vv8ni3iseulo.apps.googleusercontent.com',
    iosBundleId: 'com.example.deepPlantApp.RunnerTests',
  );
}
